# coding: utf-8

from __future__ import division, print_function, unicode_literals, \
    absolute_import

"""
This module implements classes for generating Lammps data files.
TODO: add unittests
"""

import six
from six.moves import range
from six.moves import zip
from io import open
import math

from pymatgen.core.structure import Molecule, Structure

from rubicon.io.amber.antechamber import AntechamberRunner

__author__ = 'Kiran Mathew, Navnidhi Rajput'


class LammpsData(object):
    """
    Write the lammps data file for the given molecule and box size.
    The default data file format corresponds to atom_style = atomic. If the
    molecule has the "charge" site property then the data file will be written
    in the format that corresponds to atom_style = charge

    Args:
        molecule (Molecule): molecule
        box_size (list): size of the box that embeds the packed molecule.
            [x_min, y_min, z_min, x_max, y_max, z_max]
    """

    def __init__(self, molecule, box_size):
        self.box_size = box_size
        box_lengths = [box_size[dim + 3] - box_size[dim] for dim in range(3)]
        self.boxed_molecule = None
        self.atoms_data = []
        # be defensive about the box size
        if isinstance(molecule, Molecule):
            self.boxed_molecule = molecule.get_boxed_structure(*box_lengths)
        elif isinstance(molecule, Structure):
            max_length = max(self.boxed_molecule.lattice.abc)
            max_box_size = max(box_lengths)
            self.boxed_molecule = Molecule.from_sites(self.boxed_molecule.sites)
            if max_length < max_box_size:
                self.boxed_molecule = \
                    self.boxed_molecule.get_boxed_structure(*box_lengths)
            else:
                self.boxed_molecule = \
                    self.boxed_molecule.get_boxed_structure(max_length,
                                                            max_length, max_length)
        else:
            raise ValueError("molecule must be an object of Molecule or "
                             "Structure ")
        self._set_basic_system_info()
        self._set_atoms_data()

    def _set_basic_system_info(self):
        """
        basic system info such as number of atoms, atom types, masses and
        box size
        """
        self.natoms = len(self.boxed_molecule)
        self.natom_types = len(self.boxed_molecule.symbol_set)
        self.box_size = [0, self.boxed_molecule.lattice.a, 0,
                         self.boxed_molecule.lattice.b, 0,
                         self.boxed_molecule.lattice.c]
        self.atomic_masses = [[i+1, site.specie.data["Atomic mass"]]
                              for i, site in enumerate(self.boxed_molecule)]

    def _set_atoms_data(self):
        """
        atoms data:
        atom_id, atom_type, charge(if present), x, y, z
        """
        for i, site in enumerate(self.boxed_molecule):
            atom_type = self.boxed_molecule.symbol_set.index(
                site.species_string)
            if hasattr(site, "charge"):
                self.atoms_data.append([i + 1, atom_type + 1, site.charge,
                                        site.x, site.y, site.z])
            else:
                self.atoms_data.append([i + 1, atom_type + 1, site.x,
                                        site.y, site.z])

    @staticmethod
    def set_lines_from_list(lines, block_name, input_list):
        """
        append paramter coefficient and paramter data values to the lines list
        """
        lines.append("\n" + block_name + " \n")
        _ = [lines.append(" ".join([str(x) for x in ad])) for ad in input_list]

    def __str__(self):
        """
        string representation of LammpsData
        """
        lines = []
        lines.append("Data file generated by rubicon\n")
        lines.append("{} atoms\n".format(self.natoms))
        lines.append("{} atom types\n".format(self.natom_types))
        lines.append("{} {} xlo xhi\n{} {} ylo yhi\n{} {} zlo zhi".format(
            *self.box_size))
        self.set_lines_from_list(lines, "Masses", self.atomic_masses)
        self.set_lines_from_list(lines, "Atoms", self.atoms_data)
        return '\n'.join(lines)

    def write_data_file(self, filename):
        """
        write lammps data input file
        """
        with open(filename, 'w') as f:
            f.write(self.__str__())


class LammpsForceFieldData(LammpsData):
    """
    Sets Lammps data input file from force field parameters

    Args:
        mols (list): list of Molecule objects
        mols_number (list): list of number of each type of molecule in mols
            list
        box_size (list): size of the box that embeds the packed molecule.
            [x_min, y_min, z_min, x_max, y_max, z_max]
        molecule (Molecule): the molecule generated from the molecules in mols list with
            the numbers from mols_number list(Packmol can be used to generate the molecule)
        forcefield (ForceField): force field parameters
        topologies (list): list of Topology objects for each molecule in mols
    """

    def __init__(self, mols, mols_number, box_size, molecule, forcefield, topologies):
        self.mols = mols
        self.mols_number = mols_number
        self.box_size = box_size
        self.molecule = molecule
        self.forcefield = forcefield
        self.topologies = topologies
        super(LammpsForceFieldData, self).__init__(self.molecule, self.box_size)
        # system stats
        self.nbond_types = 0
        self.nangle_types = 0
        self.ndih_types = 0
        self.nimdih_types = 0
        self.ndih = 0
        self.nbonds = 0
        self.nangles = 0
        self.nimdihs = 0
        # coefficients and maps
        self.bond_coeffs = []
        self.pair_coeffs = []
        self.angle_coeffs = []
        self.dihedral_coeffs = []
        self.improper_coeffs = []
        self.bond_map = {}
        self.angles_map = {}
        self.dihedral_map = {}
        self.imdihedral_map = {}
        # data
        self.atoms_data = []
        self.bonds_data = []
        self.angles_data = []
        self.dihedrals_data = []
        self.imdihedrals_data = []
        # set the system info, parameter coefficients and the parameter data
        self._set_system_info()
        self._set_coeffs()
        self._set_data()

    def _set_system_info(self):
        """
        set the system information. It comprises of the number of atoms,
        number of molecules, box size, number of bond types/bonds, number of
        angle types/angles, number of dihedral types/dihedrals and the
        number of improper dihedral types/improper dihedrals.
        """
        self.nbond_types = len(self.forcefield.bonds)
        self.nangle_types = len(self.forcefield.angles)
        if self.forcefield.dihedrals:
            self.ndih_types = len(self.forcefield.dihedrals)
        if self.forcefield.imdihedrals:
            self.nimdih_types = len(self.forcefield.imdihedrals)
        for mol_type, top in enumerate(self.topologies):
            self.nbonds += len(top.bonds) * self.mols_number[mol_type]
            self.nangles += len(top.angles) * self.mols_number[mol_type]
            if top.dihedrals:
                self.ndih += len(top.dihedrals) * self.mols_number[mol_type]
            if top.imdihedrals:
                self.nimdihs += len(top.imdihedrals) * self.mols_number[mol_type]

    def _set_coeffs(self):
        """
        set the coefficients for pair potentials, bonds, angles and dihedrals using the force
        field object.
        Also sets up the map between the molecule type in self.mols list and the
        parameter type and the parameter label.
        For example: bond_map maps each molecule type to {bond_key(or label) : unique bond number}
        i.e {mol_type: {bond_key : unique bond number}}.

        note: mol_type starts from 0
        """
        bond_id_offset = 0
        angle_id_offset = 0
        vdw_id_offset = 0
        dih_id_offset = 0
        imdih_id_offset = 0
        for mol_type in range(len(self.mols)):
            self.bond_coeffs, self.bond_map[mol_type] = \
                self._get_param_coeff("bonds", bond_id_offset)
            self.angle_coeffs, self.angles_map[mol_type] = \
                self._get_param_coeff("angles", angle_id_offset)
            self.pair_coeffs, _ = \
                self._get_param_coeff("vdws", vdw_id_offset)
            if self.ndih_types > 0:
                self.dihedral_coeffs, self.dihedral_map[mol_type] = \
                    self._get_param_coeff("dihedrals", dih_id_offset)
            if self.nimdih_types > 0:
                self.improper_coeffs, self.imdihedral_map[mol_type] = \
                    self._get_param_coeff("imdihedrals", imdih_id_offset)

    def _get_param_coeff(self, param_name, offset):
        """
        get the parameter coefficients from the force field

        Args:
            param_name (str): name of the parameter for which the coefficient are to be set.
            offset (int): the offset used to assign a unique id(starting from 0) to each
                parameter value

        Returns:
            [[unique paramter id, parameter values, ... ], ... ] and
            {paramter key: parameter id,...]}
        """
        if hasattr(self.forcefield, param_name):
            mapping = {}
            param = getattr(self.forcefield, param_name)
            param_coeffs = []
            param_id_offset = offset
            if param:
                for i, param_vals in enumerate(param.values()):
                    param_id = param_id_offset + i
                    param_coeffs.append([param_id+1] + list(param_vals))
                    mapping[param.keys()[i]] = param_id
                offset += len(param)
            return param_coeffs, mapping
        else:
            raise AttributeError

    def _set_data(self):
        """
        set atoms, bonds, angles and dihedral data
        """
        self._set_atoms_data()
        self.bonds_data = self._get_param_data("bonds", self.bond_map)
        self.angles_data = self._get_param_data("angles", self.angles_map)
        if self.ndih > 0:
            self.dihedrals_data = self._get_param_data("dihedrals", self.dihedral_map)
        if self.nimdihs:
            self.imdihedrals_data = self._get_param_data("imdihedral", self.imdihedral_map)

    def _set_atoms_data(self):
        """
        set the atoms data:
        [atom id, mol type, atom type, charge, x, y, z]
        where atom id is the global atom id, mol type is the type of the
        molecule(from mols list).
        Also sets up the maps 'atom_to_mol' and 'atom_to_global_molid'.
        'atom_to_mol' --> { global atom id : [ mol type, local atom id], ... }.
        'molid_to_atomid' --> [ [gloabal atom id 1, id 2, ..], ...], the index will
        be the global mol id
        """
        self.atom_to_mol = {}
        self.molid_to_atomid = []
        nmols = len(self.mols)
        shift = [0] + [len(self.mols[i]) * self.mols_number[i] for i in range(nmols - 1)]
        # set up map atom_id --> [mol_type, local atom id in the mol] in self.mols
        # set up map gobal molecule id --> [[atom_id,...],...]
        for mol_type in range(nmols):
            natoms = len(self.mols[mol_type])
            for num_mol_id in range(self.mols_number[mol_type]):
                tmp = []
                for mol_atom_id in range(natoms):
                    atom_id = num_mol_id * natoms + mol_atom_id + shift[mol_type]
                    self.atom_to_mol[atom_id] = [mol_type, mol_atom_id]
                    tmp.append(atom_id)
                self.molid_to_atomid.append(tmp)
        # set atoms data from the final molecule assembly(the packed molecule
        # obtained from packmol using the molecules from mols list and the
        # molecule numbers from mol_number list).
        # atom id, mol id, atom type, charge from topology, x, y, z
        for i, site in enumerate(self.molecule):
            atom_type = self.molecule.symbol_set.index(
                site.species_string) + 1
            atom_id = i + 1
            mol_type = self.atom_to_mol[i][0] + 1
            mol_atom_id = self.atom_to_mol[i][1] + 1
            charge = 0.0
            if hasattr(self.topologies[0], "charges"):
                if self.topologies[mol_type - 1].charges:
                    charge = self.topologies[mol_type - 1].charges[mol_atom_id - 1][0]
            self.atoms_data.append([atom_id, mol_type, atom_type, charge,
                                    site.x, site.y, site.z])

    def _get_param_data(self, param_name, param_map):
        """
        set the data for the parameter named param_name

        Args:
            param_name (str): parameter name, example: "bonds"
            param_map (dict): { mol_type: {parameter_key : unique global parameter id, ... }, ... }
                example: {0: {("c1","c2"): 1}} ==> c1-c2 bond in mol_type=0 has the global id of 1

        Returns:
            [parameter id, parameter type, global atom id1, global atom id2, ...]
        """
        nmols = len(self.mols)
        shift = [0] + [len(self.mols[i]) * self.mols_number[i] for i in range(nmols - 1)]
        mol_id = 0
        # set the map param_to_mol:
        # {global param_id :[global mol id, mol_type, local param id in the param], ... }
        param_to_mol = {}
        for mol_type in range(nmols):
            param_obj = getattr(self.topologies[mol_type], param_name)
            nparams = len(param_obj)
            for num_mol_id in range(self.mols_number[mol_type]):
                mol_id += 1
                for mol_param_id in range(nparams):
                    param_id = num_mol_id * nparams + mol_param_id + shift[mol_type]
                    param_to_mol[param_id] = [mol_id - 1, mol_type, mol_param_id]
        # set the parameter data using the topology info
        # example: loop over all bonds in the system
        param_data = []
        for param_id, pinfo in param_to_mol.items():
            mol_id = pinfo[0] # global molecule id
            mol_type = pinfo[1] # type of molecule
            mol_param_id = pinfo[2] # local parameter id in that molecule
            # example: get the bonds list for mol_type molecule
            param_obj = getattr(self.topologies[mol_type], param_name)
            # connectivity info(local atom ids and type) for the parameter with the local id
            # 'mol_param_id'. example: single bond = [i, j, bond_type]
            param = param_obj[mol_param_id]
            param_atomids = []
            # loop over local atom ids that constitute the parameter for the molecule type, mol_type
            # example: single bond = [i,j,bond_label]
            for atomid in param[:-1]:
                # local atom id to global atom id
                global_atom_id = self.molid_to_atomid[mol_id][atomid-1]
                param_atomids.append(global_atom_id+1)
            param_type = param[-1]
            # example: get the unique number id for the bond_type
            param_type_id = param_map[mol_type][param_type]
            param_data.append([param_id+1, param_type_id+1] + param_atomids)
        return param_data

    def __str__(self):
        """
        returns a string of lammps data input file
        """
        lines = []
        # title
        lines.append("Data file generated by rubicon\n")
        # count
        lines.append("{} atoms".format(self.natoms))
        lines.append("{} bonds".format(self.nbonds))
        lines.append("{} angles".format(self.nangles))
        lines.append("{} dihedrals".format(self.ndih))
        lines.append("{} impropers\n".format(self.nimdihs))
        # types
        lines.append("{} atom types".format(self.natom_types))
        lines.append("{} bond types".format(self.nbond_types))
        lines.append("{} angle types".format(self.nangle_types))
        lines.append("{} dihedral types".format(self.ndih_types))
        lines.append("{} improper types\n".format(self.nimdih_types))
        # box size
        lines.append("{} {} xlo xhi\n{} {} ylo yhi\n{} {} zlo zhi".format(*self.box_size))
        # masses
        self.set_lines_from_list(lines, "Masses", self.atomic_masses)
        # coefficients
        self.set_lines_from_list(lines, "Pair Coeffs", self.pair_coeffs)
        self.set_lines_from_list(lines, "Bond Coeffs", self.bond_coeffs)
        self.set_lines_from_list(lines, "Angle Coeffs", self.angle_coeffs)
        self.set_lines_from_list(lines, "Dihedral Coeffs", self.dihedral_coeffs)
        self.set_lines_from_list(lines, "Improper Coeffs", self.improper_coeffs)
        # data
        self.set_lines_from_list(lines, "Atoms", self.atoms_data)
        self.set_lines_from_list(lines, "Bonds", self.bonds_data)
        self.set_lines_from_list(lines, "Angles", self.angles_data)
        self.set_lines_from_list(lines, "Dihedrals", self.dihedrals_data)
        self.set_lines_from_list(lines, "Impropers", self.imdihedrals_data)
        return '\n'.join(lines)

    @staticmethod
    def from_amber(mols, mols_number, box_size, packed_molecule, gaussian_files):
        """
        WARNING: The antechamber interface is messed up.

        Use the gaussian output file and the Antechamber tool to generate the
        force field and the topology data for the lammps calculation.

        Args:
            gaussian_files (list): list of gaussian output filenames, one for each molecule
                in the mols list.
        """
        acr = AntechamberRunner(mols)
        amber_ffs = acr.get_gaussian_ff_top(gaussian_files)
        topologies = [amber_ff.topology for amber_ff in amber_ffs]
        forcefields = [amber_ff.force_field for amber_ff in amber_ffs]
        return LammpsForceFieldData(mols, mols_number, box_size, packed_molecule, forcefields,
                                    topologies)


class LammpsAmberData_to_delete(LammpsData):
    """
    Sets Lammps data input file using antechamber(amber) generated force field
    parameters
    Args:
        mols (list): list of Molecule objects
        mols_number (list): list of number of each type of molecule in mols
            list
        box_size (list): size of the box that embeds the packed molecule.
            [x_min, y_min, z_min, x_max, y_max, z_max]
        packed_molecule (Molecule): the packed molecules generated by the
            Packmol using the molecules in mols list
        gaussian_file (str): the name of gaussian output file that will be
            used by Antechamber to generate the force field parameters
    """

    def __init__(self, mols, mols_number, box_size, packed_molecule,
                 gaussian_file):
        self.mols = mols
        self.mols_number = mols_number
        self.box_size = box_size
        self.packed_molecule = packed_molecule
        self.gaussian_file = gaussian_file
        self.lines = []
        self.num_improper_dihedrals = None
        self._generate_data()
        box_lengths = [box_size[dim + 3] - box_size[dim] for dim in range(3)]
        super(LammpsAmberData_to_delete, self).__init__(self.packed_molecule,
                                                        box_lengths)

    def _generate_data(self):
        """
        Use the gaussian output file and the Antechamber tool to generate the
        force field and the topology data for the lammps calculation.
        """
        acr = AntechamberRunner(self.mols)
        self.ffmol_list = acr.get_ff_top_mol(self.mols, self.gaussian_file)

    def _set_gff_types(self, ffmol_list):
        """
        set force field information about number of atom types, bond types etc.
        """
        lines = []
        num_dih = 0
        num_atoms_types = 0
        num_bonds_types = 0
        num_angles_types = 0
        num_dihedrals_types = 0
        num_impropers_types = 0
        atom_type_list = []
        bond_type_list = []
        angle_type_list = []
        dihedral_type_list = []
        improper_type_list = []
        lines.append('LAMMPS data File\n')
        for mol, num_mols in zip(self.mols, self.mols_number):
            lines.append("{} {} {} {}".format('#', num_mols,
                                              mol.site_properties["mol_name"][
                                                  0],
                                              "molecules"))

        for ffmol in ffmol_list:
            gff = ffmol.gff
            atom_type_list.extend(list(gff.masses.keys()))
            bond_type_list.extend(list(gff.bonds.keys()))
            angle_type_list.extend(list(gff.angles.keys()))
            dihedral_type_list.extend(list(gff.dihedrals.keys()))
            improper_type_list.extend(list(gff.imdihedrals.keys()))
            num_atoms_types = len(set(atom_type_list))
            num_bonds_types += len(gff.bonds)
            num_angles_types += len(gff.angles)
            num_impropers_types += (len(gff.imdihedrals))
            for k, v in six.iteritems(gff.dihedrals):
                num_dih += len(v)
        num_dihedrals_types += num_dih
        lines.append('\n')
        lines.append("{} {}".format(num_atoms_types, "atom types"))
        lines.append("{} {}".format(num_bonds_types, "bond types"))
        lines.append("{} {}".format(num_angles_types, "angle types"))
        lines.append("{} {}".format(num_dihedrals_types, "dihedral types"))
        lines.append(
            "{} {}{}".format(num_impropers_types, "improper types", '\n'))
        self.num_improper_dihedrals = num_impropers_types
        self.lines.extend(lines)
        return '\n'.join(lines)

    def _set_top_types(self, ffmol_list):
        """
        set force field information about number of atom types, bond types etc.
        """
        lines = []
        num_atoms = 0
        num_bonds = 0
        num_angles = 0
        num_dihedrals = 0
        num_impropers = 0
        num_total_dih = 0
        for ffmol, num_mols in zip(ffmol_list, self.mols_number):
            gff = ffmol.gff
        top = ffmol.top
        top._get_ff_dihedrals(gff.dihedrals, top.dihedrals, gff.atom_gaff)
        num_atoms += (len(top.atoms)) * num_mols
        num_bonds += len(top.bonds * num_mols)
        num_angles += (len(top.angles) * num_mols)
        num_impropers += (len(top.imdihedrals) * num_mols)

        for k, n in six.iteritems(top.topdihedralff):
            num_total_dih += len(n[1])
        num_dihedrals += (num_total_dih * num_mols)
        lines.append("{} {}".format(num_atoms, "atoms"))
        lines.append("{} {}".format(num_bonds, "bonds"))
        lines.append("{} {}".format(num_angles, "angles"))
        lines.append("{} {}".format(num_dihedrals, "dihedrals"))
        lines.append(
            "{} {}{}".format(num_impropers, "impropers",
                             '\n'))
        self.lines.extend(lines)
        return '\n'.join(lines)

    def _set_box_dimensions(self):
        """
        set force field information about number of atom types, bond types etc.
        """
        lines = []
        lines.append(
            "{} {} {}".format(self.box_size[0],
                              self.box_size[3],
                              "xlo xhi"))
        lines.append(
            "{} {} {}".format(self.box_size[1],
                              self.box_size[4],
                              "ylo yhi"))
        lines.append(
            "{} {} {}{}".format(self.box_size[2],
                                self.box_size[5],
                                "zlo zhi", '\n'))

        self.lines.extend(lines)
        return '\n'.join(lines)

    def _set_masses(self, ffmol_list):
        lines = []
        num_atoms = 0
        mol_index = 1
        element_list = []
        lines.append('Masses\n')
        for ffmol, mol, num_mols in zip(ffmol_list, self.mols,
                                        self.mols_number):
            gff = ffmol.gff
            if gff.masses is not None:
                for i, v in enumerate(gff.masses.values()):
                    if list(gff.masses.keys())[i] in element_list:
                        continue
                    element_list.append(list(gff.masses.keys())[i])
                    lines.append(
                        '{} {} {} {} {} {}'.format(num_atoms + 1, v, '#',
                                                   list(gff.masses.keys())[i],
                                                   mol_index,
                                                   mol.site_properties[
                                                       "mol_name"][0]))
                    num_atoms = num_atoms + 1
            mol_index += 1
        lines.append('\n')
        self.lines.extend(lines)
        return '\n'.join(lines)

    def _set_pair_coeffs(self, ffmol_list):
        lines = []
        num_atoms = 0
        mol_index = 1
        element_list = []
        lines.append('Pair Coeffs\n')
        for ffmol, mol in zip(ffmol_list, self.mols):
            gff = ffmol.gff
            top = ffmol.top
            if gff.vdws:
                for i, v in enumerate(gff.vdws.values()):
                    if list(gff.vdws.keys())[i] in element_list:
                        continue
                    element_list.append(list(gff.vdws.keys())[i])
                    lines.append(
                        '{} {} {} {} {} {} {}'.format(num_atoms + 1, v[1],
                                                      v[0] * 1.7818, '#',
                                                      list(gff.vdws.keys())[i],
                                                      mol_index,
                                                      mol.site_properties[
                                                          "mol_name"][0]))
                    num_atoms = num_atoms + 1
            mol_index += 1
        if len(lines) == 1:
            return ''
        lines.append('\n')
        self.lines.extend(lines)
        return '\n'.join(lines)

    def _set_bond_coeffs(self, ffmol_list):

        lines = []
        num_atoms = 0
        element_list = []
        mol_index = 1
        lines.append('Bond Coeffs\n')
        for ffmol, mol in zip(ffmol_list, self.mols):
            gff = ffmol.gff
            if gff.bonds:
                for i, v in enumerate(gff.bonds.values()):
                    lines.append(
                        '{} {}  {} {} {} {} {} {}'.format(num_atoms + 1, v[0],
                                                          v[1], '#',
                                                          list(
                                                              gff.bonds.keys())[
                                                              i][
                                                              0],
                                                          list(
                                                              gff.bonds.keys())[
                                                              i][
                                                              1],
                                                          mol_index,
                                                          mol.site_properties[
                                                              "mol_name"][0]))
                    num_atoms = num_atoms + 1
            mol_index += 1
        if len(lines) == 1:
            return ''
        lines.append('\n')
        self.lines.extend(lines)
        return '\n'.join(lines)

    def _set_angle_coeffs(self, ffmol_list):
        lines = []
        num_atoms = 0
        element_list = []
        mol_index = 1
        lines.append('Angle Coeffs\n')
        for ffmol, mol in zip(ffmol_list, self.mols):
            gff = ffmol.gff
            top = ffmol.top
            if gff.angles:
                for i, v in enumerate(gff.angles.values()):
                    lines.append(
                        '{} {} {} {} {} {} {} {} {}'.format(num_atoms + 1,
                                                            v[0],
                                                            v[1], '#',
                                                            list(
                                                                gff.angles.keys())[
                                                                i][
                                                                0],
                                                            list(
                                                                gff.angles.keys())[
                                                                i][
                                                                1],
                                                            list(
                                                                gff.angles.keys())[
                                                                i][
                                                                2], mol_index,
                                                            mol.site_properties[
                                                                "mol_name"][
                                                                0]))
                    num_atoms = num_atoms + 1
            mol_index += 1
        if len(lines) == 1:
            return ''
        lines.append('\n')
        self.lines.extend(lines)
        return '\n'.join(lines)

    def _set_dihedral_coeffs(self, ffmol_list):
        lines = []
        num_atoms = 0
        j = 0
        element_list = []
        mol_index = 1
        lines.append('Dihedral Coeffs\n')
        for ffmol, mol in zip(ffmol_list, self.mols):
            gff = ffmol.gff
            top = ffmol.top
            if gff.dihedrals is not None:
                for i, v in enumerate(gff.dihedrals.values()):
                    for func_form, d in six.iteritems(v):
                        j += 1
                        lines.append(
                            '{}  {}  {}  {} {} {} {} {} {} {} {} {}'.format(j,
                                                                            d[
                                                                                0],
                                                                            func_form,
                                                                            int(
                                                                                d[
                                                                                    1]),
                                                                            '0.0',
                                                                            '#',
                                                                            list(
                                                                                gff.dihedrals.keys())[
                                                                                i][
                                                                                0],
                                                                            list(
                                                                                gff.dihedrals.keys())[
                                                                                i][
                                                                                1],
                                                                            list(
                                                                                gff.dihedrals.keys())[
                                                                                i]
                                                                            [
                                                                                2],
                                                                            list(
                                                                                gff.dihedrals.keys())[
                                                                                i][
                                                                                3],
                                                                            mol_index,
                                                                            mol.site_properties[
                                                                                "mol_name"][
                                                                                0]))
            mol_index += 1
        if len(lines) == 1:
            return ''
        lines.append('\n')
        self.lines.extend(lines)
        return '\n'.join(lines)

    def _set_improper_coeffs(self, ffmol_list):
        lines = []
        num_atoms = 0
        element_list = []
        mol_index = 1
        lines.append('Improper Coeffs\n')
        for ffmol, mol in zip(ffmol_list, self.mols):
            gff = ffmol.gff
            top = ffmol.top
            if gff.imdihedrals:
                for i, v in enumerate(gff.imdihedrals.values()):
                    lines.append('{} {}  {}  {} {} {} {} {} {} {} {}'.format
                                 (num_atoms + 1, v[0],
                                  int(round(math.cos(math.degrees(v[1])), 0)),
                                  int(v[2]), '#',
                                  list(gff.imdihedrals.keys())[i][0],
                                  list(gff.imdihedrals.keys())[i][1],
                                  list(gff.imdihedrals.keys())[i][2],
                                  list(gff.imdihedrals.keys())[i][3],
                                  mol_index,
                                  mol.site_properties["mol_name"][0]))
                    num_atoms = num_atoms + 1
            mol_index += 1
        if len(lines) == 1:
            return ''
        lines.append('\n')
        self.lines.extend(lines)
        return '\n'.join(lines)

    def _set_atom(self, ffmol_list):
        """
        set the Atoms section in lammps data file
        """
        lines = []
        element_list = []
        num_atoms = 0
        masses_index = 0
        atom_type_index = {}
        lines.append('Atoms\n')
        self.box_mol_index = []
        i = 0
        mol_index = 0
        for ffmol, mol, num_mols in zip(ffmol_list, self.mols,
                                        self.mols_number):
            gff = ffmol.gff
            top = ffmol.top
            if gff.masses is not None:
                for m, v in enumerate(gff.masses.values()):
                    if list(gff.masses.keys())[m] in element_list:
                        continue
                    element_list.append(list(gff.masses.keys())[m])
                    masses_index = masses_index + 1
                    atom_type_index[list(gff.masses.keys())[m]] = masses_index
            num_atoms = len(mol)
            num_this_mol = num_mols

            # iterate every molecule of molecule type
            for imol in range(num_mols):
                mol_coords = self.packed_molecule.cart_coords[
                             i:i + num_atoms]
                mol_index += 1
                d = {}
                for k, v in enumerate(mol_coords):
                    lines.append(
                        '{}  {}  {}  {}  {}  {} {} {}  {} {} {} {}'.format(
                            k + i + 1,
                            mol_index,
                            atom_type_index[
                                gff.atom_index_gaff
                                [
                                    k + 1].lower()], str(top.charges[k][0])
                            ,
                            v[0], v[1],
                            v[2], '#',
                            mol_index,
                            gff.atom_index_gaff[
                                k + 1],
                            gff.atom_index[
                                k + 1],
                            mol.site_properties["mol_name"][0]))
                    d[gff.atom_index[k + 1]] = k + i + 1

                self.box_mol_index.append(d)
                i += num_atoms
        lines.append('\n')
        self.lines.extend(lines)
        return '\n'.join(lines)

    def _set_bonds(self, ffmol_list):
        """
        set the Bonds section in lammps data file
        """
        lines = []
        bond_index = 0
        bond_type_index = {}
        i = 0
        mol_index = 0
        lines.append('Bonds\n')
        for ffmol, mol, num_mols in zip(ffmol_list, self.mols,
                                        self.mols_number):
            gff = ffmol.gff
            top = ffmol.top
            if gff.bonds:
                for m, v in enumerate(gff.bonds.values()):
                    bond_index = bond_index + 1
                    bond_type_index[list(gff.bonds.keys())[m]] = bond_index

            for imol in range(num_mols):
                mol_bonds = top.bonds
                mol_index += 1
                for k, v in enumerate(mol_bonds):
                    a = gff.atom_gaff[top.bonds[k][0]]
                    b = gff.atom_gaff[top.bonds[k][1]]
                    bond_label = tuple(sorted([a, b]))
                    lines.append(
                        '{} {} {} {} {} {} {} {} {}'.format((i + k + 1),
                                                            bond_type_index[
                                                                bond_label],
                                                            self.box_mol_index[
                                                                mol_index - 1][
                                                                v[0]],
                                                            self.box_mol_index[
                                                                mol_index - 1][
                                                                v[1]],
                                                            '#',
                                                            mol_index,
                                                            top.bonds[k][
                                                                0],
                                                            top.bonds[k][
                                                                1],
                                                            mol.site_properties[
                                                                "mol_name"][
                                                                0]))
                i += len(top.bonds)
        if len(lines) == 1:
            return ''
        lines.append('\n')
        self.lines.extend(lines)
        return '\n'.join(lines)

    def _set_angles(self, ffmol_list):
        """
        set the Angles section in lammps data file
        """
        lines = []
        angle_type_index = {}
        angle_index = 0
        i = 0
        mol_index = 0
        lines.append('Angles\n')
        for ffmol, mol, num_mols in zip(ffmol_list, self.mols,
                                        self.mols_number):
            gff = ffmol.gff
            top = ffmol.top
            if gff.angles:
                for m, v in enumerate(gff.angles.values()):
                    angle_index = angle_index + 1
                    angle_type_index[list(gff.angles.keys())[m]] = angle_index
            # iterate over first molecule
            for imol in range(num_mols):
                mol_angles = top.angles
                mol_index += 1
                # iterate over bonds in first molecule
                for k, v in enumerate(top.angles):
                    a = gff.atom_gaff[top.angles[k][0]]
                    b = gff.atom_gaff[top.angles[k][1]]
                    c = gff.atom_gaff[top.angles[k][2]]
                    angle_label = (a, b, c)
                    if angle_label[0] > angle_label[2]:
                        angle_label = tuple(reversed(list(angle_label)))
                    lines.append('{}  {}  {}  {}  {}  {}  {}  {}  {}  {} {}'
                                 .format(i + k + 1,
                                         angle_type_index[angle_label],
                                         self.box_mol_index[mol_index - 1][
                                             v[0]],
                                         self.box_mol_index[mol_index - 1][
                                             v[1]],
                                         self.box_mol_index[mol_index - 1][
                                             v[2]], '#',
                                         mol_index,
                                         top.angles[k][0], top.angles[k][1],
                                         top.angles[k][2],
                                         mol.site_properties["mol_name"][0]))

                i += len(top.angles)
        if len(lines) == 1:
            return ''
        lines.append('\n')
        self.lines.extend(lines)
        return '\n'.join(lines)

    def _set_dihedrals(self, ffmol_list):
        """
        set the Dihedrals section in lammps data file
        """
        lines = []
        dihedral_index = 0
        dihedral_type_index = {}
        i = 0
        j = 0
        l = 0
        mol_index = 0
        lines.append('Dihedrals\n')
        for ffmol, mol, num_mols in zip(ffmol_list, self.mols,
                                        self.mols_number):
            gff = ffmol.gff
            top = ffmol.top
            if gff.dihedrals is not None:
                for m, v in enumerate(gff.dihedrals.values()):
                    dihedral_index = dihedral_index + 1
                    dihedral_type_index[
                        list(gff.dihedrals.keys())[m]] = dihedral_index

                top._get_ff_dihedrals(gff.dihedrals, top.dihedrals,
                                      gff.atom_gaff)
                for imol in range(num_mols):
                    mol_dihedrals = top.topdihedralff
                    mol_index += 1
                    l += 1
                    # iterate over bonds in first molecule
                    for k, v in six.iteritems(top.topdihedralff):
                        A = k.split()[0]
                        B = k.split()[1]
                        C = k.split()[2]
                        D = k.split()[3]
                        a = gff.atom_gaff[k.split()[0]]
                        b = gff.atom_gaff[k.split()[1]]
                        c = gff.atom_gaff[k.split()[2]]
                        d = gff.atom_gaff[k.split()[3]]
                        dihedral_label = (a, b, c, d)

                        if dihedral_label[0] > dihedral_label[3]:
                            dihedral_label = tuple(
                                reversed(list(dihedral_label)))
                        for func_form, d in six.iteritems(v[1]):
                            j += 1
                            lines.append(
                                '{}  {}  {}  {}  {}  {}  {}  {}  {}'
                                    .format(j, dihedral_type_index[
                                    dihedral_label],
                                            self.box_mol_index[mol_index - 1][
                                                A],
                                            self.box_mol_index[mol_index - 1][
                                                B],
                                            self.box_mol_index[mol_index - 1][
                                                C],
                                            self.box_mol_index[mol_index - 1][
                                                D],
                                            '#', mol_index,
                                            mol.site_properties["mol_name"][
                                                0]))
                    i += len(top.dihedrals)
        if len(lines) == 1:
            return ''
        lines.append('\n')
        self.lines.extend(lines)
        return '\n'.join(lines)

    def _set_imdihedrals(self, ffmol_list):
        """
        set the Improper Dihedral section in lammps data file
        """
        lines = []
        imdihedral_type_index = {}
        imdihedrals_index = 0
        i = 0
        j = 0
        mol_index = 0

        lines.append('Impropers\n')
        for ffmol, mol, num_mols in zip(ffmol_list, self.mols,
                                        self.mols_number):
            gff = ffmol.gff
            top = ffmol.top
            if gff.imdihedrals is not None:
                for m, v in enumerate(gff.imdihedrals.values()):
                    imdihedrals_index = imdihedrals_index + 1
                    imdihedral_type_index[
                        list(gff.imdihedrals.keys())[m]] = imdihedrals_index

                # iterate over types of mol
                # iterate over first molecule
                for imol in range(num_mols):
                    mol_impropers = top.imdihedrals
                    mol_index += 1
                    # iterate over improper dihedrals in first molecule
                    for k, v in enumerate(top.imdihedrals):
                        j += 1
                        a = gff.atom_gaff[top.imdihedrals[k][0]]
                        b = gff.atom_gaff[top.imdihedrals[k][1]]
                        c = gff.atom_gaff[top.imdihedrals[k][2]]
                        d = gff.atom_gaff[top.imdihedrals[k][3]]
                        imdihedral_label = tuple([a, b, c, d])
                        lines.append(
                            '{}  {}  {}  {}  {}  {}  {}  {}  {}  {}  {}  {} {}'
                                .format(j, imdihedral_type_index[
                                imdihedral_label],
                                        self.box_mol_index[mol_index - 1][
                                            v[0]],
                                        self.box_mol_index[mol_index - 1][
                                            v[1]],
                                        self.box_mol_index[mol_index - 1][
                                            v[2]],
                                        self.box_mol_index[mol_index - 1][
                                            v[3]],
                                        '#', mol_index,
                                        top.imdihedrals[k][0],
                                        top.imdihedrals[k][1],
                                        top.imdihedrals[k][2],
                                        top.imdihedrals[k][3],
                                        mol.site_properties["mol_name"][0]))
                    i += len(top.imdihedrals)
        if len(lines) == 1:
            return ''
        lines.append('\n')
        self.lines.extend(lines)
        return '\n'.join(lines)

    def __str__(self):
        """
        returns a string of lammps data input file
        """
        my_lammps_list = []
        my_lammps_list.append(
            self._set_gff_types(self.ffmol_list))
        my_lammps_list.append(
            self._set_top_types(self.ffmol_list))
        my_lammps_list.append(self._set_box_dimensions())
        my_lammps_list.append(
            self._set_masses(self.ffmol_list))
        my_lammps_list.append(
            self._set_pair_coeffs(self.ffmol_list))
        my_lammps_list.append(
            self._set_bond_coeffs(self.ffmol_list))
        my_lammps_list.append(
            self._set_angle_coeffs(self.ffmol_list))
        my_lammps_list.append(
            self._set_dihedral_coeffs(self.ffmol_list))
        my_lammps_list.append(
            self._set_improper_coeffs(self.ffmol_list))
        my_lammps_list.append(
            self._set_atom(self.ffmol_list))
        my_lammps_list.append(
            self._set_bonds(self.ffmol_list))
        my_lammps_list.append(
            self._set_angles(self.ffmol_list))
        my_lammps_list.append(
            self._set_dihedrals(self.ffmol_list))
        my_lammps_list.append(
            self._set_imdihedrals(self.ffmol_list))

        return '\n'.join(my_lammps_list)

    def write_data_file(self, filename=None):
        """
        write lammps data input file
        """
        with open(filename, 'w') as f:
            f.write(self.__str__())
