#!/usr/bin/env python

# coding: utf-8

from __future__ import division, print_function, unicode_literals, \
    absolute_import

import rubicon.scripts.cancel_submissions as cancel_submissions

cancel_submissions.main()
