#!/usr/bin/env python
# coding: utf-8

from __future__ import division, print_function, unicode_literals, \
    absolute_import

from rubicon.scripts.submissions_run_eg import go_eg_submissions

if __name__ == '__main__':
    go_eg_submissions()