#!/usr/bin/env python
# coding: utf-8

from __future__ import division, print_function, unicode_literals, \
    absolute_import

__author__ = 'xiaohuiqu'

import rubicon.utils.ion_arranger.ion_arranger as ion_arranger

if __name__ == '__main__':
    ion_arranger.main()