#!/usr/bin/env python
# coding: utf-8

from __future__ import division, print_function, unicode_literals, \
    absolute_import

__author__ = 'xiaohuiqu'

import rubicon.scripts.replace_first_qctask_coords_with_xyz as coords_replacer

if __name__ == '__main__':
    coords_replacer.main()